import type { Project } from "./types";

/**
 * Every project here is one the owner built and published. Descriptions,
 * highlights, metrics, stacks and links are taken from his own project
 * documentation; nothing is extrapolated.
 *
 * Architecture nodes describe components each system actually contains, so a
 * diagram can never claim a path the project does not have.
 *
 * `domain` drives the filter and is single-assignment: several of these span
 * more than one area, and letting a project appear under two filters would
 * make the counts dishonest.
 */
export const projects: Project[] = [
  // ---------------------------------------------------------------- Distributed
  {
    slug: "helix",
    name: "Helix",
    kicker:
      "Leaderless, tunably-consistent distributed key-value store with its own LSM engine",
    domain: "Distributed systems",
    featured: true,
    context: "Personal project",
    problem:
      "A key-value store with no leader has to answer a hard question on every request: which replicas count as enough, and what happens when they disagree. Helix answers it with quorum reads and writes over a consistent-hash ring, and repairs divergence in the background rather than pretending it does not happen.",
    highlights: [
      "Leaderless, tunably-consistent store across 11 internal Go packages, with consistent-hash partitioning at 128 virtual nodes per node and quorum replication (configurable N/R/W, default 3/2/2) plus read-repair to satisfy read-your-writes",
      "LSM-tree storage engine built from first principles: CRC-framed write-ahead log with crash-safe tail truncation, a concurrent skip-list memtable, sorted on-disk SSTables with bloom filters and a block cache, and background compaction",
      "gRPC data and membership plane over Protocol Buffers with optional mutual TLS, exposing coordinated get, put and delete through any node plus a read-only admin API for status, ring and membership introspection",
      "SWIM gossip membership with failure detection and eventual convergence, and anti-entropy through hinted handoff and Merkle-tree reconciliation to repair replica divergence without a central coordinator",
      "Stateless HTTP gateway aggregating per-node status, membership, ring and parsed Prometheus metrics, streaming live snapshots to browsers over Server-Sent Events with constant-time bearer auth and single-origin CORS",
      "Next.js 14 operator console with a server-side BFF proxy that keeps the operator token out of the browser, showing live overview, membership reconciliation, metrics charts and a base64-aware KV browser",
      "Distributed behaviour validated with a deterministic simulation, chaos and load-testing harness, alongside Prometheus metrics, health and readiness endpoints and structured logging",
      "Four-layer console test suite (unit, route, jsdom component, and Playwright end-to-end), with the first three gated in CI",
      "CI/CD on GitHub Actions running race-enabled tests, lint and typecheck on every push, publishing images to GHCR and deploying on version tags, mirrored on GCP Cloud Build",
      "Reproducible infrastructure via a Helm chart (StatefulSet with stable per-pod DNS), raw Kubernetes manifests, and Terraform modules for local kind and GKE",
      "Always-on production topology at zero infrastructure cost, exposing only the console through a Cloudflare Tunnel with no open inbound ports, with encrypted off-host backups to S3-compatible storage",
    ],
    metrics: [
      { value: "11", label: "internal Go packages" },
      { value: "128", label: "virtual nodes per physical node" },
      { value: "3/2/2", label: "default replication N/R/W" },
      { value: "0", label: "open inbound ports in production" },
    ],
    stack: [
      "Go",
      "gRPC",
      "Protocol Buffers",
      "LSM-tree",
      "SWIM gossip",
      "Merkle trees",
      "Next.js 14",
      "Docker",
      "Kubernetes",
      "Helm",
      "Terraform",
      "Prometheus",
    ],
    architecture: {
      caption: "Coordinated write path",
      nodes: [
        { id: "client", label: "Any node", detail: "gRPC entry", kind: "client" },
        { id: "ring", label: "Hash ring", detail: "128 vnodes", kind: "app" },
        { id: "quorum", label: "Quorum", detail: "N/R/W 3/2/2", kind: "transport" },
        { id: "lsm", label: "LSM engine", detail: "WAL, memtable", kind: "compute" },
        { id: "sst", label: "SSTables", detail: "bloom, cache", kind: "data" },
      ],
    },
    links: { repo: "https://github.com/Talif787/helix" },
  },
  {
    slug: "distributed-backtesting-engine",
    name: "Distributed financial backtesting engine",
    kicker:
      "Raft consensus written from scratch in C++17, with zero external dependencies",
    domain: "Distributed systems",
    featured: true,
    context: "CS 6650, Building Scalable Distributed Systems",
    period: "Fall 2025",
    problem:
      "Backtesting a strategy across hundreds of securities scales linearly: double the securities, double the runtime. Worse, a single crash at hour three of a four-hour job costs you everything. The engineering problem is not the maths, it is surviving the crash and keeping a controller cluster in agreement about what has already been computed.",
    ownership:
      "I owned the controller architecture, the Raft controller integration, the binary message protocol and the SMA strategy: roughly 2,300 of the 8,500 lines.",
    collaborators: [
      {
        name: "Mohamed Samir Shafat Khan",
        scope: "Raft node and log, worker, checkpoint manager",
      },
    ],
    highlights: [
      "Fault-tolerant three-node controller cluster implementing Raft from scratch: leader election with randomised 150 to 300ms timeouts, 50ms heartbeats, and durable term, vote and log persistence, verified across three live processes",
      "Custom binary TCP protocol with length-prefixed framing and network-byte-order serialisation, on a thread-per-connection model with least-loaded scheduling to parallelise backtests across worker nodes",
      "Raft RPC layer (RequestVote, AppendEntries) with log matching, conflict-entry truncation and majority-based commit advancement, persisting each node's log to disk and reloading on startup to survive crashes",
      "Heartbeat-based worker failure detection at a 6-second timeout with automatic job re-queueing, plus a binary checkpoint and restart mechanism so interrupted backtests resume from the last snapshot",
      "Multithreaded SMA-crossover engine computing total return, 252-day annualised Sharpe ratio and maximum drawdown per symbol, with in-memory CSV time-series caching to evaluate symbols in parallel",
      "Test and evaluation harness of 7 C++ test binaries and 6 automated evaluation scripts covering correctness, multi-worker scheduling, controller failover and checkpoint persistence",
      "Least-loaded worker selection measured at 30% better throughput than round-robin when job sizes vary",
      "Checkpoints written every 100 symbols using a temp file and atomic rename, holding overhead under 1% of execution time",
    ],
    metrics: [
      { value: "8,500", label: "lines of C++17 across 62 files" },
      { value: "7.5s", label: "average failover over 10 trials" },
      { value: "3.98x", label: "speedup on four workers" },
      { value: "84%", label: "smaller payloads than JSON" },
    ],
    stack: [
      "C++17",
      "Raft consensus",
      "TCP sockets",
      "POSIX threads",
      "CMake",
      "Linux cluster",
    ],
    architecture: {
      caption: "Job path",
      nodes: [
        { id: "client", label: "Client", detail: "CSV jobs", kind: "client" },
        {
          id: "wire",
          label: "Binary TCP",
          detail: "length-prefixed",
          kind: "transport",
        },
        {
          id: "control",
          label: "Raft controller",
          detail: "3 nodes, 1 leader",
          kind: "app",
        },
        {
          id: "workers",
          label: "Worker pool",
          detail: "least-loaded",
          kind: "compute",
        },
        { id: "ckpt", label: "Checkpoints", detail: "atomic writes", kind: "data" },
      ],
    },
    links: {
      repo: "https://github.com/Talif787/distributed-financial-backtesting-raft/tree/main/Project",
    },
  },
  {
    slug: "payments-ledger",
    name: "Real-time payments ledger with fraud detection",
    kicker:
      "Double-entry bookkeeping where the database itself refuses to let the books go unbalanced",
    domain: "Distributed systems",
    featured: true,
    context: "Personal project",
    problem:
      "A ledger has one job that cannot be negotiated: money must be conserved. That means correctness comes before availability on the posting path, and it means a fraud service that goes down must never be able to block money movement. Those two requirements pull in opposite directions, so the system draws an explicit boundary between them.",
    highlights: [
      "Correctness-first double-entry ledger in Java and Spring Boot, enforcing money conservation through SERIALIZABLE-isolation posting with retry, a deferred balanced-postings database trigger, and construction-time invariants",
      "Exactly-once money movement using client idempotency keys with request fingerprinting: replays return the original result, key reuse with a changed body yields a 409 conflict",
      "Event-driven architecture across ledger, reconciliation and fraud services communicating via a transactional outbox to Kafka, with consumer-side deduplication turning at-least-once delivery into exactly-once effects",
      "Independent reconciliation service that re-derives balances from the Kafka event stream and cross-checks three independent derivations plus global conservation, converting silent balance corruption into an alarmable drift metric",
      "Real-time fraud screening combining deterministic rules with a logistic-regression model deployed in shadow mode, scored and logged without enforcing until config-activated, with streaming velocity and spend features in Redis",
      "An explicit CP/AP fault-tolerance boundary: the consistent ledger consults the availability-first fraud service inline with a strict timeout and fails open, so a fraud outage never blocks a payment",
      "OAuth2 JWT resource-server security enforcing RBAC by scope and ABAC by token claims (per-transaction amount ceilings, account allowlists), plus per-subject token-bucket rate limiting made chart-configurable via Helm",
      "Distributed tracing across HTTP and Kafka with OpenTelemetry to Jaeger, structured ECS JSON logging with correlation IDs, and Prometheus metrics across all three services",
      "Next.js operator console proxying all traffic server-side to preserve a zero-CORS boundary and keep the signing secret off the browser, across a double-entry composer, reconciliation and fraud screens",
      "Helm chart on Kubernetes with Terraform provisioning (free local kind apply plus cost-gated GKE and Cloud SQL) and GitHub Actions test-and-build on every push",
      "Framework-free correctness suite validating ledger invariants, the outbox relay, the reconciliation three-way check and the fraud combiner, plus a 30-test Vitest frontend suite, with same-account serializable concurrency verified under parallel load",
    ],
    metrics: [
      { value: "3", label: "independent balance derivations cross-checked" },
      { value: "409", label: "returned on idempotency key reuse" },
      { value: "CP/AP", label: "explicit consistency boundary" },
    ],
    stack: [
      "Java",
      "Spring Boot",
      "PostgreSQL",
      "Apache Kafka",
      "Redis",
      "OpenTelemetry",
      "Jaeger",
      "Next.js",
      "Kubernetes",
      "Helm",
      "Terraform",
    ],
    architecture: {
      caption: "Posting path",
      nodes: [
        { id: "req", label: "Request", detail: "idempotency key", kind: "client" },
        { id: "ledger", label: "Ledger", detail: "SERIALIZABLE", kind: "app" },
        {
          id: "outbox",
          label: "Outbox to Kafka",
          detail: "exactly-once",
          kind: "transport",
        },
        {
          id: "recon",
          label: "Reconciliation",
          detail: "3-way check",
          kind: "compute",
        },
        { id: "books", label: "Books", detail: "balanced, audited", kind: "data" },
      ],
    },
    links: {
      demo: "https://ledger-console-five.vercel.app/",
      repo: "https://github.com/Talif787/payments-ledger",
    },
  },
  {
    slug: "event-driven-order-fulfillment",
    name: "Event-driven order fulfillment platform",
    kicker:
      "Six microservices across two languages, coordinated by an orchestration saga",
    domain: "Distributed systems",
    featured: false,
    context: "Personal project",
    problem:
      "An order touches inventory, payment, fulfillment and notification, and any one of them can fail after the others have already committed. Without a saga and compensating transactions you get orders that are paid for but never shipped.",
    highlights: [
      "Six services (order, inventory, payment, fulfillment, notification and a saga orchestrator) in Go and Java/Spring Boot, coordinating a distributed order lifecycle through an orchestration-based saga with compensating transactions",
      "Effectively-once event processing over Apache Kafka using the transactional outbox pattern, idempotent consumers, optimistic concurrency control and per-consumer dead-letter queues",
      "Database-per-service architecture on PostgreSQL with CQRS read models projected from the Kafka event stream, isolating data ownership and enabling independent scaling",
      "OpenTelemetry distributed tracing propagated across both Kafka and HTTP boundaries in all six services, plus Prometheus metrics and Grafana dashboards, giving end-to-end visibility into one order's path",
      "Full cloud footprint as infrastructure-as-code with Terraform (AWS EKS, networking) and a reusable Helm chart covering pod security, autoscaling and disruption budgets",
      "Path-filtered GitHub Actions CI/CD that builds, tests and validates only the changed services and event schemas",
      "Cross-service contracts governed by a versioned JSON Schema registry validated in CI, preventing breaking schema changes from reaching consumers",
      "React and TypeScript operations console that places orders and renders the live saga as a real-time lifecycle timeline, polling four service read models to visualise both confirmation and compensation paths",
      "Console deployed to Cloudflare's edge network with the entire twenty-container backend packaged as a one-command launch via Docker Compose and dev containers",
    ],
    metrics: [
      { value: "6", label: "microservices, two languages" },
      { value: "4", label: "Kafka topics under schema governance" },
      { value: "20", label: "containers, one-command launch" },
    ],
    stack: [
      "Go",
      "Java",
      "Spring Boot",
      "Apache Kafka",
      "PostgreSQL",
      "React",
      "TypeScript",
      "Kubernetes",
      "Helm",
      "Terraform",
      "AWS EKS",
      "Grafana",
    ],
    architecture: {
      caption: "Order lifecycle",
      nodes: [
        {
          id: "order",
          label: "Order service",
          detail: "accepts, outboxes",
          kind: "app",
        },
        { id: "kafka", label: "Kafka", detail: "4 topics", kind: "transport" },
        {
          id: "saga",
          label: "Saga orchestrator",
          detail: "compensating",
          kind: "compute",
        },
        {
          id: "svcs",
          label: "Inventory, payment, fulfillment",
          detail: "db per service",
          kind: "compute",
        },
        { id: "cqrs", label: "CQRS read models", detail: "projected", kind: "data" },
      ],
    },
    links: {
      demo: "https://64d9395d.order-fulfillment-console.pages.dev/",
      repo: "https://github.com/Talif787/event-driven-order-fulfillment",
    },
  },
  // -------------------------------------------------------- Platform engineering
  {
    slug: "forge",
    name: "Forge",
    kicker: "Cloud-native internal developer platform with its own Kubernetes operator",
    domain: "Platform engineering",
    featured: true,
    context: "Personal project",
    problem:
      "An internal developer platform has to turn a declared intent into real cluster resources, repeatedly, without drifting. That means a reconciliation loop rather than a deploy script, and a provisioning workflow that can compensate when step four fails after steps one through three already committed.",
    highlights: [
      "Go control-plane API exposing catalog, tenant and application domains as bounded-context modules over a versioned REST surface, with optimistic concurrency via If-Match versioning and idempotent writes via Idempotency-Key headers",
      "Kubernetes operator with a custom Application CRD that reconciles declared specs into Deployments, Services and observability ConfigMaps using server-side apply, achieving idempotent drift-correcting reconciliation verified by envtest integration tests against a real API server",
      "Event-driven backbone using the transactional outbox pattern, persisting domain events atomically with state changes in PostgreSQL and relaying them to NATS JetStream, eliminating dual-write inconsistency",
      "Durable tenant-provisioning saga on Temporal with compensation on failure, exposing workflow execution state through the control-plane API via Temporal's visibility API",
      "Admission control combining CEL validation rules on the CRD with Kyverno cluster policies that block latest-tag images and enforce resource limits and non-root execution, plus per-pod security contexts dropping all Linux capabilities",
      "Next.js 15 portal unifying catalog, tenants, applications and provisioning behind a backend-for-frontend proxy that mints tokens server-side, keeping credentials off the client and eliminating CORS exposure",
      "Frontend data layer with TanStack Query and Zod-validated responses, optimistic mutations with rollback, TanStack Table with sorting and pagination, a cmdk command palette, and graceful degradation when Kubernetes and Temporal are unavailable",
      "Control plane instrumented with OpenTelemetry tracing, Prometheus metrics, structured logging, token-bucket rate limiting and JWKS/OIDC-capable authentication, with stateless services behind connection-pooled PostgreSQL",
      "GitHub Actions CI running unit, testcontainers integration and envtest suites, deployed at zero cost across Vercel, Render and Neon from a multi-stage distroless Docker image",
    ],
    metrics: [
      { value: "1", label: "custom Kubernetes CRD, reconciled" },
      { value: "3", label: "test tiers: unit, testcontainers, envtest" },
      { value: "$0", label: "infrastructure cost in production" },
    ],
    stack: [
      "Go",
      "Kubernetes operators",
      "Temporal",
      "NATS JetStream",
      "PostgreSQL",
      "Kyverno",
      "CEL",
      "Next.js 15",
      "TypeScript",
      "OpenTelemetry",
      "Docker",
    ],
    architecture: {
      caption: "Declared spec to running workload",
      nodes: [
        { id: "portal", label: "Portal", detail: "BFF proxy", kind: "client" },
        { id: "cp", label: "Control plane", detail: "Go, versioned REST", kind: "app" },
        { id: "bus", label: "Outbox to NATS", detail: "JetStream", kind: "transport" },
        { id: "op", label: "Operator", detail: "reconciles CRD", kind: "compute" },
        { id: "k8s", label: "Cluster", detail: "Deployments, Services", kind: "data" },
      ],
    },
    links: {
      demo: "https://forge-portal-delta.vercel.app/",
      repo: "https://github.com/Talif787/forge-platform",
    },
  },
  {
    slug: "prism",
    name: "Prism",
    kicker:
      "Multi-tenant observability platform ingesting metrics, logs and traces over OTLP",
    domain: "Platform engineering",
    featured: false,
    context: "Personal project",
    problem:
      "Observability data is high-cardinality and arrives constantly, and every tenant must only ever see its own. That pushes the storage choice toward a columnar engine and pushes authorization all the way down into the request path rather than leaving it at the edge.",
    highlights: [
      "Multi-service observability backend in Go spanning control-plane, gateway, query, alerting and metering services, ingesting metrics, logs and traces over an OTLP gRPC endpoint and persisting to ClickHouse for high-cardinality analytical queries",
      "Tenant-isolated control plane exposing scoped API keys (ingest, query, admin) and role-based membership (owner, admin, editor, viewer), enforcing per-service authorization via HS256 JWT and internal service tokens across the request path",
      "Standalone Next.js 15 console with a same-origin BFF layer that keeps service credentials server-side, delivering nine screens across metrics, logs, traces, alerts, usage and tenant administration",
      "Distributed-tracing explorer that groups flat OTLP span streams by trace ID client-side and renders a per-trace waterfall from a dedicated trace-detail endpoint, with duration-proportional bars and error-status highlighting",
      "Cookie-based authentication using AES-256-GCM sealed httpOnly sessions, minting per-tenant query and admin keys on login and reissuing on tenant switch, with an authoritative logout that suppresses environment fallback",
      "Rules-driven alerting engine supporting aggregations, comparison operators, evaluation windows and severity labels, with read-time rule joins and 409-conflict handling contributed to the Go alerter to resolve denormalization and duplicate-name conflicts",
      "Metering and billing surface computing per-signal usage against plan quotas and generating closable invoices with line-item cost breakdowns",
      "Quality gate with Vitest unit and component tests and Playwright end-to-end smoke coverage, migrated to ESLint 9 flat config, enforcing typecheck, lint, build and test in GitHub Actions",
      "Full stack deployed on free-tier infrastructure, containerizing the Go services, ClickHouse, PostgreSQL and Redis with Docker Compose and exposing a public console through a zero-port Tailscale Funnel with automatic TLS",
    ],
    metrics: [
      { value: "5", label: "Go services in the backend" },
      { value: "9", label: "console screens" },
      { value: "3", label: "signal types: metrics, logs, traces" },
    ],
    stack: [
      "Go",
      "OTLP",
      "gRPC",
      "ClickHouse",
      "PostgreSQL",
      "Redis",
      "Next.js 15",
      "TypeScript",
      "TanStack Query",
      "Docker Compose",
      "Playwright",
    ],
    architecture: {
      caption: "Telemetry path",
      nodes: [
        { id: "sdk", label: "Instrumented app", detail: "OTLP export", kind: "client" },
        { id: "gw", label: "Gateway", detail: "gRPC ingest", kind: "transport" },
        { id: "ch", label: "ClickHouse", detail: "high cardinality", kind: "data" },
        { id: "q", label: "Query service", detail: "tenant-scoped", kind: "compute" },
        { id: "console", label: "Console", detail: "9 screens via BFF", kind: "app" },
      ],
    },
    links: { repo: "https://github.com/Talif787/prism" },
  },
  {
    slug: "flux",
    name: "Flux",
    kicker:
      "Distributed GPU inference control plane with metering and per-tenant budgets",
    domain: "Platform engineering",
    featured: false,
    context: "Personal project",
    problem:
      "Serving LLM inference across a pool of workers means the control plane has to know which backends exist right now, route to them, and stop a tenant that has spent its budget, all without buffering the token stream that makes the product feel fast.",
    highlights: [
      "Distributed LLM inference control plane in Python and FastAPI separating a stateful control plane from a horizontally scalable compute plane of self-registering workers that heartbeat, deregister and route OpenAI-compatible chat completions across discovered backends",
      "Multi-tenant isolation with API-key authentication and role-based authorization across six scoped roles enforced at the API layer, using pepper-hashed keys, per-tenant data scoping and suspend/reactivate lifecycle",
      "Async SQLAlchemy 2.0 and Alembic persistence over PostgreSQL with a six-migration schema, idempotency keys, tenant-scoped queries and Pydantic v2 contracts across tenancy, models, workers, metering and budgets",
      "Token-level streaming inference over Server-Sent Events end to end, proxying gateway completions through a Next.js backend-for-frontend without buffering so tokens render live while the platform API key stays server-side",
      "Usage metering, per-model pricing and per-tenant monthly budgets with serving-path enforcement returning HTTP 402 on exceed, powering a cost-reporting API aggregating tokens, request counts and computed spend",
      "Worker self-registration with a real inference backend proxying to OpenAI-compatible servers (Ollama, vLLM, OpenAI), mapping requests and streamed responses to domain types and degrading upstream failures to HTTP 502",
      "Hardened with mypy strict typing, ruff and roughly 150 automated tests across pytest, Vitest and Playwright, validating hermetic env isolation, streaming SSE parsing and budget enforcement under polluted-environment conditions",
      "Kubernetes Helm chart with HPA autoscaling and a pre-install migration hook, Terraform for GKE, Cloud SQL and Artifact Registry, and GitHub Actions publishing images to GHCR on tags",
      "Enterprise operator console in Next.js delivering tenants, keys, models, live worker telemetry, a streaming playground and usage dashboards behind a secure BFF with signed httpOnly sessions",
    ],
    metrics: [
      { value: "~150", label: "automated tests across three runners" },
      { value: "6", label: "scoped authorization roles" },
      { value: "402", label: "returned when a tenant exceeds budget" },
    ],
    stack: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "SQLAlchemy 2.0",
      "Pydantic v2",
      "Server-Sent Events",
      "Next.js",
      "Docker",
      "Kubernetes",
      "Helm",
      "Terraform",
    ],
    architecture: {
      caption: "Inference path",
      nodes: [
        { id: "client", label: "Client", detail: "API key", kind: "client" },
        { id: "cp", label: "Control plane", detail: "auth, budgets", kind: "app" },
        {
          id: "route",
          label: "Gateway",
          detail: "routes to workers",
          kind: "transport",
        },
        { id: "worker", label: "Worker", detail: "OpenAI-compatible", kind: "compute" },
        { id: "meter", label: "Metering", detail: "tokens, spend", kind: "data" },
      ],
    },
    links: {
      demo: "https://flux-console.vercel.app/",
      repo: "https://github.com/Talif787/flux",
    },
  },
  {
    slug: "conductor",
    name: "Conductor",
    kicker:
      "Agentic workflow control plane with an outbox pipeline and no message broker",
    domain: "Platform engineering",
    featured: false,
    context: "Personal project",
    problem:
      "Agent runs need atomic write-and-publish semantics, which normally means standing up a broker and an always-on worker. Conductor gets the same guarantee from a transactional outbox with an in-process relay, which is what lets the whole platform run for nothing.",
    highlights: [
      "Agentic-workflow control plane in Python and FastAPI using hexagonal architecture with strict domain, application and infrastructure boundaries, exposing versioned REST APIs for runs, workflows, tool registration, execution and human-in-the-loop approvals across an eight-migration PostgreSQL schema",
      "Transactional-outbox eventing pipeline with an in-process relay projecting run events into a CQRS read model, guaranteeing atomic write-and-publish without a separate message broker or always-on worker infrastructure",
      "JWT authentication with refresh-token rotation and RBAC enforced at the API layer, hardened by a production secret guard, security headers (HSTS, nosniff, frame-deny) and TLS-encrypted asyncpg connections",
      "Multi-stage non-root Docker image deployed via a Render Blueprint with idempotent migration-on-start, tuning Gunicorn and Uvicorn worker concurrency for a constrained 512MB runtime",
      "GitHub Actions pipeline running lint, type-check, unit and Postgres-backed integration tests and container builds as a merge gate, with supply-chain scanning via Trivy, gitleaks, Bandit and Dependabot",
      "Infrastructure as Code with Terraform managing GitHub branch protection, deployment environments and Cloudflare DNS, keeping secrets out of state",
      "Observability through OpenTelemetry tracing, a Prometheus metrics endpoint, structured JSON logging and Sentry error tracking, with external uptime monitoring on health endpoints",
      "Automated disaster recovery with a scheduled pg_dump backup workflow to versioned artifacts, achieving a 24-hour RPO and minutes-scale RTO through Neon database branching and documented restore runbooks",
      "Server-side LLM gateway with pluggable providers and per-run and per-step token-cost tracking, isolating provider credentials from the browser",
    ],
    metrics: [
      { value: "24h", label: "recovery point objective" },
      { value: "512MB", label: "production runtime footprint" },
      { value: "$0", label: "monthly cloud cost" },
    ],
    stack: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Next.js 15",
      "Docker",
      "Terraform",
      "GitHub Actions",
      "OpenTelemetry",
      "Sentry",
    ],
    architecture: {
      caption: "Run event path",
      nodes: [
        { id: "api", label: "REST API", detail: "hexagonal core", kind: "app" },
        {
          id: "outbox",
          label: "Outbox",
          detail: "same transaction",
          kind: "transport",
        },
        {
          id: "relay",
          label: "In-process relay",
          detail: "no broker",
          kind: "compute",
        },
        { id: "read", label: "CQRS read model", detail: "run history", kind: "data" },
      ],
    },
    links: {
      demo: "https://conductor-web-theta.vercel.app/",
      repo: "https://github.com/Talif787/conductor",
    },
  },
  {
    slug: "cascade",
    name: "Cascade",
    kicker:
      "Governed data platform where humans, scripts and AI agents hit the same policy layer",
    domain: "Platform engineering",
    featured: false,
    context: "Personal project",
    problem:
      "The moment an AI agent can query your data platform, every governance rule you wrote for the web console has to apply to the agent too. Reimplementing those rules per surface guarantees drift, so Cascade centralises them in one policy core that all three surfaces inherit.",
    highlights: [
      "Governed data platform control plane as a layered modular monolith (domain, application, infrastructure, interface), centralising policy enforcement in the application core so identical governance rules are inherited by every interface without per-surface reimplementation",
      "Three governed access surfaces over a single policy layer, a typed REST API, a Next.js console and a Model Context Protocol agent endpoint, with a serving-view lifecycle gate that rejects unauthorized queries identically whether the caller is a human, a script or an AI agent",
      "Governed MCP agent surface over a single JSON-RPC 2.0 endpoint exposing six data tools with runtime discovery via tools/list, rendering dynamic input forms from each tool's JSON Schema so new backend tools surface in the UI without frontend changes",
      "Next.js 15 App Router console in TypeScript spanning nine control-plane surfaces, using TanStack Query with per-domain typed API layers and a setQueryData-plus-refetch mutation pattern that keeps status-gated lifecycle controls consistent with server state",
      "Backend-for-Frontend proxy through App Router route handlers forwarding all API and MCP traffic server-side, isolating bearer credentials from the browser, eliminating CORS and exposing a same-origin surface configurable via one environment variable",
      "Async persistence with SQLAlchemy, asyncpg and Alembic over PostgreSQL, backed by Redis for caching and ephemeral state, with an idempotent seed script for repeatable provisioning from a fresh database",
      "Multiple resource lifecycles modelled as state machines (serving views, ingestion sources, processing jobs with checkpoints and savepoints, versioned data contracts with compatibility checks), with terminal-state and transition guards enforced in the core",
      "Multi-service stack deployed entirely on free-tier infrastructure (Netlify, containerized FastAPI on Render, Neon PostgreSQL, Upstash Redis over TLS), separating liveness and readiness probes so datastore cold-starts do not fail deployments",
      "Structured correlation-ID-tagged logging and problem-detail error responses, propagating human-readable governed-rejection reasons from the policy core through both REST and MCP results back to traceable server logs",
    ],
    metrics: [
      { value: "3", label: "access surfaces, one policy core" },
      { value: "6", label: "MCP tools with runtime discovery" },
      { value: "9", label: "control-plane surfaces in the console" },
    ],
    stack: [
      "Python",
      "FastAPI",
      "Model Context Protocol",
      "JSON-RPC 2.0",
      "PostgreSQL",
      "SQLAlchemy",
      "Alembic",
      "Redis",
      "Next.js 15",
      "TypeScript",
    ],
    architecture: {
      caption: "Governed query path",
      nodes: [
        {
          id: "callers",
          label: "Human, script, agent",
          detail: "3 surfaces",
          kind: "client",
        },
        {
          id: "bff",
          label: "REST, console, MCP",
          detail: "one entry each",
          kind: "transport",
        },
        { id: "policy", label: "Policy core", detail: "lifecycle gate", kind: "app" },
        { id: "data", label: "Serving views", detail: "PostgreSQL", kind: "data" },
      ],
    },
    links: {
      demo: "https://resonant-souffle-b88564.netlify.app/",
      repo: "https://github.com/Talif787/cascade",
    },
  },

  // ------------------------------------------------------------------ AI systems
  {
    slug: "eka",
    name: "Enterprise Knowledge Assistant",
    kicker:
      "Production RAG with hybrid retrieval, streamed answers and inline citations",
    domain: "AI systems",
    featured: false,
    context: "Personal project",
    problem:
      "A retrieval system that only does vector similarity misses exact terms, and one that only does full-text misses meaning. EKA runs both and fuses them, then makes every sentence in the answer traceable back to the passage it came from, because an ungrounded answer is worse than no answer.",
    highlights: [
      "Production retrieval-augmented knowledge assistant as a modular monolith with hexagonal, domain-driven boundaries across six bounded contexts (documents, ingestion, retrieval, generation, identity, evaluation), enforcing inward-only dependencies so contexts extract into services without rewrites",
      "Asynchronous ingestion pipeline in Python and FastAPI that chunks, embeds and indexes documents via a Redis-backed queue with a background worker, idempotency keyed on content hash, retry with backoff and dead-letter handling",
      "Hybrid retrieval combining pgvector similarity search with PostgreSQL full-text search, fused and re-ranked with a Redis cache layer, exposing embeddings and generation behind pluggable ports so a local implementation swaps for a hosted model without application changes",
      "Token-streamed answering service over Server-Sent Events returning grounded responses with inline source citations, and a Next.js 15 and React 19 frontend rendering a live grounding rail that links each citation marker to its originating passage",
      "Multi-tenant authentication with verified JWTs where tenant scope is derived server-side from token claims rather than client input, isolating every query, document and citation per tenant",
      "Full-stack TypeScript frontend using App Router, TanStack Query, Zustand and React Hook Form with Zod, covering every backend endpoint with documents, search, streaming answers, a live ingestion monitor, a KPI dashboard and a command palette",
      "Structured JSON logging bound to correlation IDs and OpenTelemetry tracing, with quality enforced through 100 unit and integration tests plus an offline evaluation harness gating retrieval and grounding metrics in CI",
      "API and worker containerized as a multi-stage non-root image and deployed to Fly.io with managed Neon PostgreSQL and Upstash Redis, running Alembic expand-then-contract migrations as a release step for zero-downtime rollouts",
      "Deployment as infrastructure-as-code with a Fly.io process-group configuration for API and worker, plus a Helm chart and Terraform for a Kubernetes path with a free local kind option",
    ],
    metrics: [
      { value: "6", label: "bounded contexts, inward-only deps" },
      { value: "100", label: "unit and integration tests" },
      { value: "2", label: "retrieval strategies fused and re-ranked" },
    ],
    stack: [
      "Python",
      "FastAPI",
      "pgvector",
      "PostgreSQL full-text search",
      "Redis",
      "Server-Sent Events",
      "Next.js 15",
      "React 19",
      "Fly.io",
      "Alembic",
      "OpenTelemetry",
    ],
    architecture: {
      caption: "Answer path",
      nodes: [
        { id: "q", label: "Query", detail: "tenant-scoped", kind: "client" },
        {
          id: "hybrid",
          label: "Hybrid retrieval",
          detail: "vector + FTS",
          kind: "compute",
        },
        {
          id: "rerank",
          label: "Fuse and re-rank",
          detail: "Redis cache",
          kind: "transport",
        },
        { id: "gen", label: "Generation", detail: "SSE stream", kind: "app" },
        { id: "cite", label: "Grounding rail", detail: "passage links", kind: "data" },
      ],
    },
    links: {
      demo: "https://eka-frontend-five.vercel.app/",
      repo: "https://github.com/Talif787/eka-knowledge-assistant",
    },
  },
  {
    slug: "intelligent-bistro",
    name: "The Intelligent Bistro",
    kicker:
      "Natural-language restaurant ordering where the LLM never touches the prices",
    domain: "AI systems",
    featured: false,
    context: "Personal project",
    problem:
      "Letting a language model mutate a shopping cart directly means a hallucinated item name becomes a real charge. The fix is to keep the model on one side of a boundary: it proposes structured actions, and a deterministic server-side resolver maps them to canonical menu IDs and does the pricing.",
    highlights: [
      "Full-stack conversational restaurant ordering platform on Expo React Native and Node.js/Express, translating free-form natural language into deterministic cart mutations through an LLM tool-calling pipeline with server-side action resolution",
      "Provider-agnostic AI service layer abstracting Groq (Llama 3.3 70B), Anthropic Claude, Google Gemini and local Ollama behind a unified callWithTool interface, enabling one-line model swaps via environment variable with zero business-logic changes",
      "Structured tool-calling pattern forcing the model to invoke a single update_cart function against a strict JSON schema, a discriminated union of ADD_ITEM, REMOVE_ITEM, UPDATE_QUANTITY and CLEAR_CART, guaranteeing parseable output across four heterogeneous providers",
      "Server-side resolution pipeline isolating the model from the trusted-pricing path, using a custom fuzzy matcher (Levenshtein similarity plus Jaccard token overlap) to map free text to canonical menu IDs and prevent hallucinations from corrupting cart integrity",
      "Shared OpenAI-compatible adapter unifying Groq, Ollama and any wire-compatible endpoint into one implementation with typed error handling for network failures, non-2xx responses and malformed tool arguments",
      "Zustand cart architecture with pure-function reducers, deduplicating cart lines via composite keys and funnelling both UI-driven and AI-driven mutations through a single applyActions bottleneck for auditability",
      "Jest suite of 60 tests across five files covering the fuzzy matcher, menu service, action resolver, HTTP routes via Supertest and multi-provider adapters, mocking all external SDK calls for API-key-free CI",
      "Express API hardened with Zod validation, Helmet, CORS enforcement, structured JSON logging and per-endpoint token-bucket rate limiting scoped to the LLM-expensive chat route for cost control",
      "Stateless backend with client-owned cart and conversation state, so every request self-contains the context the model needs and the service scales horizontally without sessions",
      "Fuzzy matcher optimised with anti-false-positive guards rejecting short consonant-similar strings, for example caviar against Caesar Salad, verified by regression tests for typo tolerance, alias resolution and off-menu queries",
      "Mobile UI in NativeWind with React Navigation 7, Expo Haptics and Linear Gradient, applying safe-area handling, KeyboardAvoidingView orchestration and optimistic pending-bubble UX",
    ],
    metrics: [
      { value: "4", label: "interchangeable LLM providers" },
      { value: "60", label: "Jest tests, no API key needed" },
      { value: "1", label: "tool function the model may call" },
    ],
    stack: [
      "TypeScript",
      "React Native",
      "Expo",
      "NativeWind",
      "Node.js",
      "Express",
      "Zustand",
      "Groq",
      "Anthropic Claude",
      "Google Gemini",
      "Ollama",
      "Zod",
      "Jest",
    ],
    architecture: {
      caption: "Utterance to cart",
      nodes: [
        { id: "app", label: "Mobile app", detail: "Expo, Zustand", kind: "client" },
        { id: "api", label: "Express API", detail: "rate limited", kind: "app" },
        {
          id: "llm",
          label: "LLM tool call",
          detail: "one function",
          kind: "transport",
        },
        {
          id: "resolve",
          label: "Fuzzy resolver",
          detail: "canonical IDs",
          kind: "compute",
        },
        { id: "cart", label: "Cart", detail: "trusted pricing", kind: "data" },
      ],
    },
    links: { repo: "https://github.com/Talif787/viridien-intelligent-bistro" },
  },

  // -------------------------------------------------------------------- Products
  {
    slug: "meridian",
    name: "Meridian",
    kicker:
      "Multi-tenant B2B SaaS with tenant isolation enforced by the database itself",
    domain: "Products",
    featured: false,
    context: "Personal project",
    problem:
      "In multi-tenant SaaS, a single missing WHERE clause leaks one customer's data to another. Meridian moves the guarantee below the application, into PostgreSQL row-level security bound to a restricted role, so an application bug cannot cross a tenant boundary.",
    highlights: [
      "Production multi-tenant B2B SaaS with a NestJS API on Node 22 and a Next.js 15 frontend, enforcing tenant isolation at the database layer through PostgreSQL row-level security bound to a restricted role and per-transaction tenant context",
      "Backend-for-frontend authentication layer holding JWT access and refresh tokens in httpOnly cookies and proxying server-to-server to the API, eliminating token exposure to the browser and removing the cross-origin CORS surface entirely",
      "Role-based authorization (owner, admin, member) across every domain module using guard-enforced policies, including owner-only-owner mutation rules and last-owner protection, backed by an append-only audit log",
      "Stripe-backed billing with plan entitlements and feature gating, driving subscription upgrades and cancellations through verified production webhooks that update plan state and return 402 for premium features on unentitled tenants",
      "Asynchronous background processing on BullMQ over Redis with retry, exponential backoff, a dead-letter queue and scheduled maintenance sweeps, exposed through an owner-only operations dashboard of live queue counts",
      "Containerized backend deployed to Google Cloud Run with scale-to-zero, secrets in Secret Manager, a least-privilege runtime service account and images built via Cloud Build, on managed Neon PostgreSQL and Upstash Redis",
      "Cloud backend provisioned as reproducible infrastructure with Terraform defining the Cloud Run service, Artifact Registry, secret containers and IAM, keeping secret values out of state",
      "OpenTelemetry tracing and metrics, structured request-scoped logging, Kubernetes-style liveness and readiness probes, and CI on GitHub Actions with typecheck, tests and container publishing to GHCR",
      "Full operator console (projects, members, invitations, billing, feature flags, audit log, queues) with TanStack Query, React Hook Form and Zod, using tenant-scoped caching and a server-redirect workspace switch to guarantee correct data on tenant change",
    ],
    metrics: [
      { value: "RLS", label: "isolation enforced in PostgreSQL" },
      { value: "3", label: "roles: owner, admin, member" },
      { value: "402", label: "returned for unentitled premium features" },
    ],
    stack: [
      "TypeScript",
      "NestJS",
      "Next.js 15",
      "PostgreSQL",
      "Row-level security",
      "Redis",
      "BullMQ",
      "Stripe",
      "Google Cloud Run",
      "Terraform",
      "OpenTelemetry",
    ],
    architecture: {
      caption: "Tenant-scoped request",
      nodes: [
        { id: "browser", label: "Browser", detail: "httpOnly cookies", kind: "client" },
        {
          id: "bff",
          label: "Next.js BFF",
          detail: "no CORS surface",
          kind: "transport",
        },
        { id: "api", label: "NestJS API", detail: "guards, RBAC", kind: "app" },
        { id: "rls", label: "PostgreSQL RLS", detail: "restricted role", kind: "data" },
      ],
    },
    links: {
      demo: "https://meridian-web-dun.vercel.app/",
      repo: "https://github.com/Talif787/meridian",
    },
  },
  {
    slug: "realtime-chat",
    name: "Real-time chat and collaboration platform",
    kicker: "Discord-style messaging with RBAC, WebRTC channels and a polling fallback",
    domain: "Products",
    featured: false,
    context: "Personal project",
    problem:
      "Group chat breaks in the gaps: a message that arrives twice, a member list that lags behind who is actually in the room, a dropped socket that silently stops delivery. The interesting work is keeping socket state and database state agreeing while people are typing.",
    highlights: [
      "Full-stack multi-tenant real-time messaging platform on Next.js 15 App Router and React 19, modelling servers, channels, members, conversations and messages across a normalised seven-table Prisma and MySQL schema with indexed foreign keys, enums and cascade-delete integrity",
      "Bidirectional real-time messaging for group channels and 1:1 direct messages using a persistent Socket.IO server hosted in the Next.js Pages Router, broadcasting create, edit and soft-delete events to synchronise all connected clients instantly",
      "Three-tier RBAC model (ADMIN, MODERATOR, GUEST) enforced at the API layer, gating member kicks, role reassignment, channel management and message moderation",
      "Cursor-based infinite-scroll message history with TanStack Query useInfiniteQuery, paginating in batches of 10 and applying optimistic cache mutations from Socket.IO events to render new and edited messages without full refetches",
      "Client hardened against dropped WebSocket connections with an automatic one-second polling fallback while the socket is disconnected, preserving message continuity during transient network interruptions",
      "LiveKit integration for audio and video channels, minting scoped JWT access tokens server-side via the LiveKit Server SDK with room-join, publish and subscribe grants, rendering low-latency WebRTC conferencing",
      "Clerk authentication with middleware-based route protection, resolving each request to a server-side profile and enforcing server-membership validation before any message, channel or member operation executes",
      "Authenticated file-attachment uploads for images and PDFs through an UploadThing file router with server-side auth middleware and CDN-backed delivery, with configurable size and count limits",
      "Keyboard-driven command-palette search across channels and members using cmdk, alongside shareable invite-code onboarding with owner-gated, UUID-regenerable unique codes",
      "Type-safe accessible UI with shadcn/ui and Radix primitives on Tailwind CSS v4, Zustand modal state, React Hook Form with Zod validation and next-themes theming",
      "Deployed as a persistent Node service on Render via a render.yaml Blueprint with reproducible build and start phases, a health-check endpoint and auto-deploy on main, backed by distributed MySQL on TiDB Serverless",
    ],
    metrics: [
      { value: "7", label: "normalised tables with cascade integrity" },
      { value: "3", label: "RBAC tiers enforced at the API" },
      { value: "1s", label: "polling fallback when the socket drops" },
    ],
    stack: [
      "TypeScript",
      "Next.js 15",
      "React 19",
      "Socket.IO",
      "Prisma",
      "MySQL",
      "TiDB Serverless",
      "LiveKit",
      "Clerk",
      "UploadThing",
      "TanStack Query",
      "Tailwind CSS v4",
    ],
    architecture: {
      caption: "Message path",
      nodes: [
        { id: "client", label: "Client", detail: "React 19", kind: "client" },
        { id: "app", label: "Next.js 15", detail: "auth, RBAC", kind: "app" },
        {
          id: "socket",
          label: "Socket.IO",
          detail: "polling fallback",
          kind: "transport",
        },
        { id: "orm", label: "Prisma", detail: "7-table schema", kind: "compute" },
        { id: "db", label: "TiDB MySQL", detail: "distributed", kind: "data" },
      ],
    },
    links: {
      demo: "https://realtime-chat-dcwo.onrender.com/",
      repo: "https://github.com/Talif787/discord-clone",
    },
  },
  {
    slug: "collaborative-editor",
    name: "Collaborative document editor",
    kicker: "Conflict-free concurrent editing on Yjs CRDTs, with no central locking",
    domain: "Products",
    featured: false,
    context: "Personal project",
    problem:
      "Two people editing one paragraph is the whole problem. Every keystroke has to reach everyone else fast enough that nobody notices the round trip, and the document has to converge on one state regardless of who typed what first. CRDTs get you there without a lock.",
    highlights: [
      "Real-time collaborative rich-text editor supporting concurrent multi-user editing of a shared document, integrating Liveblocks, Tiptap on ProseMirror, and Yjs CRDTs over WebSockets to guarantee conflict-free convergence, with experimental offline-edit support and no central locking",
      "Editing engine in React 19 composing 20+ Tiptap extensions (tables, nested task lists, resizable images, multicolour highlighting, text alignment) plus custom ProseMirror extensions for font size and line height",
      "Live collaboration layer with presence-aware avatar stacks, per-user coloured cursors, @mention resolution, text-anchored comment threads and a notification inbox, broadcasting presence at a 16ms throttle for fluid awareness",
      "Reactive serverless backend on Convex with type-safe queries and mutations, cursor-based pagination, and a full-text search index over document titles scoped by owner or organization",
      "Authentication and organization-scoped multi-tenancy using Clerk, enforcing owner and org-membership authorization inside every Convex mutation and minting scoped per-room Liveblocks access tokens through a Next.js route handler",
      "Structured on the Next.js 15 App Router using server components, route handlers, server actions and Suspense boundaries, wiring Clerk-authenticated Convex sessions to progressively stream room, user and document data on load",
      "Maintainable type-safe frontend spanning 90+ TypeScript modules and 48 reusable Radix and shadcn/ui primitives, managing editor state with Zustand, URL query state with nuqs and schema-validated forms with React Hook Form and Zod",
    ],
    metrics: [
      { value: "16ms", label: "presence broadcast throttle, ~60fps" },
      { value: "20+", label: "Tiptap extensions composed" },
      { value: "90+", label: "TypeScript modules" },
    ],
    stack: [
      "TypeScript",
      "Next.js 15",
      "React 19",
      "Convex",
      "Liveblocks",
      "Tiptap",
      "ProseMirror",
      "Yjs",
      "Clerk",
      "Zustand",
      "Zod",
    ],
    architecture: {
      caption: "Sync path",
      nodes: [
        { id: "editor", label: "Editor", detail: "Tiptap, React 19", kind: "client" },
        { id: "crdt", label: "Yjs CRDT", detail: "no locking", kind: "compute" },
        { id: "lb", label: "Liveblocks", detail: "WebSocket room", kind: "transport" },
        { id: "convex", label: "Convex", detail: "reactive queries", kind: "app" },
        { id: "doc", label: "Document", detail: "converged state", kind: "data" },
      ],
    },
    links: {
      demo: "https://google-docs-clone-ivory.vercel.app/",
      repo: "https://github.com/Talif787/google-docs-clone",
    },
  },
];
