import type { SkillGroup } from "./types";

/**
 * Grouped by the job the technology does, not by badge count. No proficiency
 * percentages: a bar chart cannot be verified, a shipped system can.
 *
 * The rule for inclusion is evidence: every entry appears in a role, a project
 * or a certification elsewhere on this page. Nothing is listed on the strength
 * of familiarity alone.
 */
export const skillGroups: SkillGroup[] = [
  {
    name: "Languages",
    description: "What I write",
    items: ["Go", "TypeScript", "Python", "Java", "C++17", "JavaScript", "C", "SQL", "R"],
  },
  {
    name: "Backend and services",
    description: "Where the logic lives",
    items: [
      "Node.js",
      "NestJS",
      "Express",
      "FastAPI",
      "Spring Boot",
      "gRPC",
      "Protocol Buffers",
      "REST APIs",
      "Server-Sent Events",
      "AWS Lambda",
    ],
  },
  {
    name: "Distributed systems",
    description: "Keeping separate machines in agreement",
    items: [
      "Raft consensus",
      "SWIM gossip",
      "Quorum replication",
      "Consistent hashing",
      "LSM-tree storage",
      "Merkle reconciliation",
      "Sagas and compensation",
      "Transactional outbox",
      "CQRS",
      "Idempotency and exactly-once",
      "Multi-threading",
    ],
  },
  {
    name: "Messaging and real-time",
    description: "Moving events and keeping clients live",
    items: [
      "Apache Kafka",
      "NATS JetStream",
      "Temporal",
      "ActiveMQ",
      "RabbitMQ",
      "AWS Kinesis",
      "BullMQ",
      "WebSockets",
      "Socket.IO",
      "Yjs CRDTs",
      "Liveblocks",
      "LiveKit",
    ],
  },
  {
    name: "Data",
    description: "Persistence, retrieval and modelling",
    items: [
      "PostgreSQL",
      "Row-level security",
      "MySQL",
      "MongoDB",
      "Redis",
      "ClickHouse",
      "Cassandra",
      "Neo4j",
      "OpenSearch",
      "SQLite",
      "pgvector",
      "Prisma",
      "SQLAlchemy",
      "Alembic",
      "Convex",
    ],
  },
  {
    name: "Cloud and infrastructure",
    description: "AWS certified, and four years shipping on it",
    items: [
      "AWS IoT FleetWise",
      "IoT Jobs",
      "Greengrass V2",
      "EC2",
      "S3",
      "Cognito",
      "CloudFormation",
      "EKS",
      "Google Cloud Run",
      "GKE",
      "Fly.io",
      "Docker",
      "Kubernetes operators",
      "Helm",
      "Terraform",
      "Kyverno",
    ],
  },
  {
    name: "AI and LLM systems",
    description: "Retrieval, evaluation, tool calling and agent surfaces",
    items: [
      "Amazon Bedrock",
      "LangChain",
      "RAG pipelines",
      "Hybrid retrieval",
      "RAGAS evaluation",
      "OpenAI API",
      "Anthropic Claude",
      "Groq",
      "Google Gemini",
      "Ollama",
      "Model Context Protocol",
      "LLM tool calling",
      "Prompt engineering",
      "Streamlit",
    ],
  },
  {
    name: "Observability",
    description: "Knowing what the system is actually doing",
    items: [
      "OpenTelemetry",
      "OTLP",
      "Prometheus",
      "Grafana",
      "Jaeger",
      "Structured logging",
      "Correlation IDs",
      "Distributed tracing",
      "Sentry",
    ],
  },
  {
    name: "Frontend",
    description: "The surface people actually touch",
    items: [
      "React",
      "Next.js",
      "React Native",
      "Expo",
      "Tailwind CSS",
      "shadcn/ui",
      "Radix UI",
      "TanStack Query",
      "Zustand",
      "Zod",
      "Recharts",
      "Mapbox",
      "Tiptap",
    ],
  },
  {
    name: "Practice",
    description: "How the work stays correct",
    items: [
      "Playwright",
      "Vitest",
      "Jest",
      "pytest",
      "testcontainers",
      "envtest",
      "GitHub Actions",
      "Jenkins",
      "Hexagonal architecture",
      "Domain-driven design",
      "Object-oriented design",
      "Agile",
      "Scrum",
      "Git",
    ],
  },
];
